# FILE: render.yaml
# Replace the existing 'services' section with this:
services:
  - type: web
    name: formation-microsoft365
    env: python
    buildCommand: pip install -r requirements.txt
    # --- MODIFIED START COMMAND ---
    # Explicitly use eventlet workers (matching Procfile intent)
    # Increase timeout to 120 seconds (adjust if needed)
    # Use a reasonable number of workers (e.g., 2-3 if plan allows, start with 1)
    startCommand: gunicorn --worker-class eventlet -w 1 --timeout 120 app:app
    # --- END MODIFIED START COMMAND ---
    envVars:
      - key: DATABASE_URL
        # Keep your existing DATABASE_URL value here
        value: postgresql://xvcyuaga:rfodwjclemtvhwvqsrpp@alpha.europe.mkdb.sh:5432/usdtdsgq
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0 # Or your desired Python version
      # Optional: Force Flask environment if needed
      # - key: FLASK_ENV
      #   value: production
